name: expense_tracker_flutter_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  intl: ^0.18.1

  fl_chart: ^1.1.1

  shared_preferences: ^2.1.1

  sqflite: ^2.2.8+4

  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  flutter_launcher_icons: ^0.13.1

#dart run flutter_launcher_icons
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/launcher_icons/expenses.png"
  min_sdk_android: 21

  web:
    generate: true
    image_path: "assets/launcher_icons/expenses.png"
    background_color: "#AABBGGRR"
    theme_color: "#AABBGGRR"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
